---
kind: pipeline
name: deploy

steps:
    - name: login
      image: node
      commands:
          - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      environment:
          NPM_TOKEN:
              from_secret: npm_token
      volumes:
          - name: npmrc
            path: /root/

    - name: install
      image: node
      commands:
          - npm i
      volumes:
          - name: npmrc
            path: /root/

    - name: build
      image: node
      commands:
          - sleep 200
          - npm run release
      volumes:
          - name: npmrc
            path: /root/
      environment:
          CASSANDRA_HOST: cassandra

    - name: publish
      image: node
      commands:
          - npm publish --access public
      when:
          event:
              - tag
      volumes:
          - name: npmrc
            path: /root/

trigger:
    event:
        - push
        - tag

volumes:
    - name: npmrc
      temp: {}

secrets:
    - source: npm_token
      target: NPM_TOKEN

services:
    - name: cassandra
      image: cassandra
